events {
    worker_connections 1024;
}

http {
    upstream bot_workers {
        # Балансировка между инстансами
        server localhost:8001;
        server localhost:8002; 
        server localhost:8003;
    }

    server {
        listen 8080;
        
        location /handle {
            proxy_pass http://bot_workers;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}