FROM python:3.11-slim

RUN apt-get update && apt-get install -y \
    curl \
    iputils-ping \
    netcat-openbsd \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Установка Python зависимостей
COPY requirements.txt .
RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

# Копирование всего кода
COPY . .

# Создание папки для логов
RUN mkdir -p /app/logs

CMD ["python", "main.py"]